# Generated by Django 5.1.7 on 2025-03-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='municipality',
            field=models.CharField(choices=[('ALY', 'Alytus'), ('KAU', 'Kaunas'), ('PAN', 'Panevėžys'), ('KLA', 'Klaipėda'), ('MAR', 'Marijampolė'), ('SIA', 'Šiauliai'), ('TAU', 'Tauragė'), ('TEL', 'Telšiai'), ('UTA', 'Utena'), ('VIL', 'Vilnius')], default='VIL', max_length=3),
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
