# Generated by Django 5.1.7 on 2025-03-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_municipality_delete_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='available_times',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ClientReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('trees_count', models.IntegerField()),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('trees_under_4m', models.BooleanField(default=False)),
                ('selected_time', models.CharField(max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
