# Generated by Django 5.1.7 on 2025-03-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_available_times_clientreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='reservations.reservation'),
        ),
    ]
