# Generated by Django 5.1.7 on 2025-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_clientreservation_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientreservation',
            name='price_per_tree',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='clientreservation',
            name='service_plan',
            field=models.CharField(choices=[('basic', 'Augalo Startas'), ('premium', 'Augalo Ilgalaikis')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='clientreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
