# Generated by Django 5.1.7 on 2025-03-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_clientreservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreservation',
            name='email',
        ),
    ]
