# Generated by Django 5.1.7 on 2025-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_clientreservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreservation',
            name='planting_required',
            field=models.CharField(choices=[('yes', 'TAIP'), ('no', 'NE')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='clientreservation',
            name='selected_time',
            field=models.CharField(max_length=20),
        ),
    ]
