# Generated by Django 5.1.7 on 2025-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_clientreservation_planting_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreservation',
            name='planting_required',
            field=models.CharField(choices=[('no', 'NE'), ('planting_only', 'TAIP, tik sodinimas'), ('planting_and_delivery', 'TAIP, augalai su pristatymu ir sodinimas')], default='no', max_length=22),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='municipality',
            field=models.CharField(choices=[('ALY', 'Alytus'), ('KAU', 'Kaunas'), ('PAN', 'Panevėžys'), ('KLA', 'Klaipėda'), ('MAR', 'Marijampolė'), ('SIA', 'Šiauliai'), ('TAU', 'Tauragė'), ('TEL', 'Telšiai'), ('UTA', 'Utena'), ('VIL', 'Vilnius'), ('UKM', 'Ukmergė'), ('PRN', 'Prienai')], default='VIL', max_length=3),
        ),
    ]
